In [7]:
import numpy as np
import sys
from sys import getsizeof as size

In [2]:
print(np.__version__)

1.25.2


In [24]:
cvalues = [20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1]
c = np.array(cvalues)
print(c)
print(type(c))
print(size(cvalues)+len(cvalues)*size(cvalues[0]))

[20.1 20.8 21.9 22.5 22.7 22.3 21.8 21.2 20.9 20.1]
<class 'numpy.ndarray'>
392


In [25]:
cvalues = []
print("Empty list size is:",size(cvalues))

Empty list size is: 56


In [147]:
from sys import getsizeof as size
lst = [20+x for x in range(41)]
size_of_1ist_object = size(lst) # only green box
size_of_e1ements = len(lst) * size(lst[0]) # 
tota1_1ist_size = size_of_1ist_object + size_of_e1ements

print("Size without the size of the elements: ", size_of_1ist_object)
print("Size of all the elements: ", size_of_e1ements)
print("Total size of list, including elements: ", tota1_1ist_size)
lstt = []
print("Empty list size is:",size(lstt))


Size without the size of the elements:  472
Size of all the elements:  1148
Total size of list, including elements:  1620
Empty list size is: 56


* 184,448,632,56
* 248,476,724,56
* every new 8 integer adds 64 bytes to list
* every new integer adds 28 bytes

In [175]:
e = np.array([])
print(size(e))

a = np.array([24, 12, 57], np.int8)
print(size(a)-112)
a = np.array([24, 12, 57], np.int16)
print(size(a) - 112)
a = np.array([24, 12, 57], np.int32)
print(size(a) - 112)
a = np.array([24, 12, 57], np.int64)
print(size(a) - 112)

a = np.array(arr, np.int8)
print(size(a) - 112)

112
3
6
12
24
120


### Size Comparison

In [222]:
arr = [x for x in range(32768)]
np_arr = np.array(arr, np.int16)

print(size(arr)+len(arr)*size(arr[0]))
print(size(np_arr)-112)

1063768
65536


In [196]:
2**16

65536

In [219]:
32768*2

65536

### Time Comparison

In [239]:
import time
size_of_vec = 10000000
def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y 
    return time.time() - t1

In [240]:
t1 = pure_python_version()
t2 = numpy_version()
print(t1, t2)
print("Numpy is in this example " + str(t1/t2) + " faster!")

1.9648845195770264 0.04500842094421387
Numpy is in this example 43.6559310092754 faster!


### General Numpy
* np.arange(start,end,step)
* np.linspace(start, stop, num=50, endpoint=True, retstep=False)
* np.ndim
* np.shape
* np.array(arr).reshape(x,y)
* np.ones((x,y)),np.zeros((x,y))

In [253]:
x = np.arange(1,10,1)
print(x)
x = np.arange(1,10,3)
print(x)
x = np.arange(0.5,3.8,0.45)
print(x)
x = np.arange(1.5,10.8,0.5, int)
print(x)

[1 2 3 4 5 6 7 8 9]
[1 4 7]
[0.5  0.95 1.4  1.85 2.3  2.75 3.2  3.65]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [257]:
## linspace(start, stop, num=50, endpoint=True, retstep=False)
x = np.linspace(1,10, 19)
print(x)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [275]:
x = np.array(45)
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
V = np.array([3.4, 6.9, 99.8, 12.8])

A = np.array([ [3.4, 8.7, 9.9],
              [1.1, -7.8, -0.7],
              [4.1, 12.3, 4.8],
              [4.1, 12.3, 4.8]])


print(np.ndim(x))
print(np.ndim(F),F.dtype,F.shape)
print(np.ndim(V),V.dtype,V.shape)
print(A.ndim,A.dtype,A.shape)


0
1 int32 (8,)
1 float64 (4,)
2 float64 (4, 3)


In [276]:
A.shape= (3,4)
print(A)
print(A.ndim,A.dtype,A.shape)

[[ 3.4  8.7  9.9  1.1]
 [-7.8 -0.7  4.1 12.3]
 [ 4.8  4.1 12.3  4.8]]
2 float64 (3, 4)


In [280]:
A = np.array ([
                [11, 12, 13, 14, 15],
                [21, 22, 23, 24, 25],
                [31, 32, 33, 34, 35],
                [41, 42, 43, 44, 45]
                ])
print(A[ :3, 2:])


[[13 14 15]
 [23 24 25]
 [33 34 35]]


In [292]:
X = np.arange(28).reshape(4,7)
XX =A.reshape(2,10)
print(X,"\n")
print(XX)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]] 

[[11 12 13 14 15 21 22 23 24 25]
 [31 32 33 34 35 41 42 43 44 45]]


In [293]:
print (X [::2, ::2])

[[ 0  2  4  6]
 [14 16 18 20]]


In [297]:
A = np.arange(12)
B = A.reshape(3, 4)
A[0] = 101
print(A,id(A))
print(B,id(B))

np.may_share_memory(A, B)

[101   1   2   3   4   5   6   7   8   9  10  11] 2184806676976
[[101   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]] 2184806676784


True

In [303]:
ones_ = np.ones((4,3))
zeros_ = np.zeros((4,3))
empty_ = np.empty((4,3))
print("Ones matrx",ones_,"\n")
print(zeros_,"\n")
print("Empty matrx",empty_,"\n")
A = np.arange(12).reshape(4,3)
print(A)
print(np.ones_like(A))
print(np.zeros_like(A))

Ones matrx [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

Empty matrx [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
