In [1]:
import numpy as np
import sys
from sys import getsizeof as size

In [2]:
print(np.__version__)

1.25.2


### Linear Algebra
* identity(n, dtype=None)
* eye(N, M=None, k=0, dtype=float)


In [3]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [4]:
np.eye(N=4,M=10,k=3,dtype=int)

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [5]:
dt = np.dtype([('density', np.int32)])
x = np.array([(393), (337), (256)],dtype=dt)
print(x)
print(x['density'])
print("\nThe internal representation:")
print(repr(x))


[(393,) (337,) (256,)]
[393 337 256]

The internal representation:
array([(393,), (337,), (256,)], dtype=[('density', '<i4')])


In [6]:
dt = np.dtype([('density', 'i4')])
x = np.array([(393), (337), (256)],dtype=dt)
print("The internal representation:")
print(repr(x))

The internal representation:
array([(393,), (337,), (256,)], dtype=[('density', '<i4')])


In [7]:
print("data size :",np.dtype(np.int64).itemsize,"BYTES |","data type",np.dtype(np.int64).name,"| order type",np.dtype(np.int64).byteorder)
print("data size :",np.dtype('d').itemsize,"BYTES |","data type",np.dtype('d').name,"| order type",np.dtype('d').byteorder)
print("data size :",np.dtype('<d').itemsize,"BYTES |","data type",np.dtype('<d').name,"| order type",np.dtype('<d').byteorder)
print("data size :",np.dtype('>d').itemsize,"BYTES |","data type",np.dtype('>d').name,"| order type",np.dtype('>d').byteorder)



data size : 8 BYTES | data type int64 | order type =
data size : 8 BYTES | data type float64 | order type =
data size : 8 BYTES | data type float64 | order type =
data size : 8 BYTES | data type float64 | order type >


In [8]:
dt = np.dtype([('country', 'S20'), ('density', 'i4'), ('area', 'i4'), ('population', 'i4')])
population_table = np.array([
('Netherlands', 393, 41526, 16928800),
('Belgium', 337, 30510, 11007020),
('United Kingdom', 256, 243610, 62262000),
('Germany', 233, 357021, 81799600),
('Liechtenstein', 205, 160, 32842),
('Italy', 192, 301230, 59715625),
('Switzerland', 177, 41290, 7301994),
('Luxembourg', 173, 2586, 512000),
('France', 111, 547030, 63601002),
('Austria', 97, 83858, 8169929),
('Greece', 81, 131940, 11606813),
('Ireland', 65, 70280, 4581269),
('Sweden', 20, 449964, 9515744),
('Finland', 16, 338424, 5410233),
('Norway', 13, 385252, 5033675)],
dtype=dt)
print(population_table['country'][0])


b'Netherlands'


In [9]:
type(population_table['country'][0])

numpy.bytes_

In [10]:
# Example byte string
b_string = b'Hello, world!'
print(b_string)

# Convert byte string to Unicode (str)
unicode_string = b_string.decode('utf-8')  # 'utf-8' is a common encoding for Unicode text
print("Unicode String:", unicode_string)


b'Hello, world!'
Unicode String: Hello, world!


In [11]:
dt = np.dtype([('country', np.str_,20),
               ('density', 'i4'), 
               ('area', 'i4'), 
               ('population', 'i4')])
population_table = np.array([
('Netherlands', 393, 41526, 16928800),
('Belgium', 337, 30510, 11007020),
('United Kingdom', 256, 243610, 62262000),
('Germany', 233, 357021, 81799600),
('Liechtenstein', 205, 160, 32842),
('Italy', 192, 301230, 59715625),
('Switzerland', 177, 41290, 7301994),
('Luxembourg', 173, 2586, 512000),
('France', 111, 547030, 63601002),
('Austria', 97, 83858, 8169929),
('Greece', 81, 131940, 11606813),
('Ireland', 65, 70280, 4581269),
('Sweden', 20, 449964, 9515744),
('Finland', 16, 338424, 5410233),
('Norway', 13, 385252, 5033675)],
dtype=dt)
print(population_table['country'][0])


Netherlands


In [15]:
np.savetxt("population_table.csv",
           population_table,
           fmt= "%s,%d,%d,%d",
           delimiter=","          
           )
dt = np.dtype([('country', np.str_,20),
               ('density', 'i4'), 
               ('area', 'i4'), 
               ('population', 'i4')])

nw_table = np.genfromtxt("population_table.csv",dtype=dt,
                         delimiter=",")
print(nw_table['country'])
print(nw_table)

['Netherlands' 'Belgium' 'United Kingdom' 'Germany' 'Liechtenstein'
 'Italy' 'Switzerland' 'Luxembourg' 'France' 'Austria' 'Greece' 'Ireland'
 'Sweden' 'Finland' 'Norway']
[('Netherlands', 393,  41526, 16928800) ('Belgium', 337,  30510, 11007020)
 ('United Kingdom', 256, 243610, 62262000)
 ('Germany', 233, 357021, 81799600)
 ('Liechtenstein', 205,    160,    32842) ('Italy', 192, 301230, 59715625)
 ('Switzerland', 177,  41290,  7301994)
 ('Luxembourg', 173,   2586,   512000) ('France', 111, 547030, 63601002)
 ('Austria',  97,  83858,  8169929) ('Greece',  81, 131940, 11606813)
 ('Ireland',  65,  70280,  4581269) ('Sweden',  20, 449964,  9515744)
 ('Finland',  16, 338424,  5410233) ('Norway',  13, 385252,  5033675)]
