### Working with shapes and axes

In [1]:
import numpy as np

In [2]:
x_lst = np.array([x for x in range(28)]).reshape(4,7)
y_lst =np.copy(x_lst)
print(x_lst)
print("Shape is :",x_lst.shape)
print("Dimension is :",np.ndim(x_lst))
print("-----------------------------------------------------")
print("Flattend is :",x_lst.flatten())
print("-----------------------------------------------------")
print("ravel is :",x_lst.ravel())
print("-----------------------------------------------------")
print("Reshaped is :",x_lst.reshape(1,28))
print(x_lst)
print("-----------------------------------------------------")
y_lst.resize((1,28))
print("resized is :",y_lst)
print("-----------------------------------------------------")
x_lst.shape = (1,28)
print("Shaped =(1,28) is :",x_lst)



[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
Shape is : (4, 7)
Dimension is : 2
-----------------------------------------------------
Flattend is : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]
-----------------------------------------------------
ravel is : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]
-----------------------------------------------------
Reshaped is : [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27]]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
-----------------------------------------------------
resized is : [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27]]
-----------------------------------------------------
Shaped =(1,28) is : [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 

In [3]:
x_lst = np.array([x for x in range(30)]).reshape(2,3,5)
print(x_lst)
print("Shape is :",x_lst.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
Shape is : (2, 3, 5)


### Axes Shift
* moveaxis
* swapaxis

In [4]:
x_reshaped = np.moveaxis(x_lst, -1, 0)
print(x_lst.shape)
print(x_reshaped.shape)
print(x_reshaped)

(2, 3, 5)
(5, 2, 3)
[[[ 0  5 10]
  [15 20 25]]

 [[ 1  6 11]
  [16 21 26]]

 [[ 2  7 12]
  [17 22 27]]

 [[ 3  8 13]
  [18 23 28]]

 [[ 4  9 14]
  [19 24 29]]]


In [7]:
x = np.array([[[0,1],
               [2,3]],
                    [[4,5],
                    [6,7]],
                         [[8,9],
                         [10,11]]])
print(x.shape)
y = np.swapaxes(x,0,2)
print(y.shape)
print(y)

(3, 2, 2)
(2, 2, 3)
[[[ 0  4  8]
  [ 2  6 10]]

 [[ 1  5  9]
  [ 3  7 11]]]


In [8]:
x[0][0]

array([0, 1])

### Transpose

In [9]:
np.array([x for x in range(6)]).reshape(2,3).T

array([[0, 3],
       [1, 4],
       [2, 5]])

### Expand dims & Squeeze

In [10]:
x = np.array([1, 2])
y = np.expand_dims(x,axis=0)
print(y,y.shape)
y = np.expand_dims(x,axis=1)
print(y,y.shape)

[[1 2]] (1, 2)
[[1]
 [2]] (2, 1)


In [11]:
x = np.array([[1, 2],
              [3, 4]])
y = np.expand_dims(x,axis=0)
print(y,y.shape)
y = np.expand_dims(x,axis=1)
print(y,y.shape)
y = np.expand_dims(x,axis=2)
print(y,y.shape)

[[[1 2]
  [3 4]]] (1, 2, 2)
[[[1 2]]

 [[3 4]]] (2, 1, 2)
[[[1]
  [2]]

 [[3]
  [4]]] (2, 2, 1)


In [23]:
A = np.array([10, 20, 30])
B = np.array([1, 2, 3])
A[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [12]:
x = np.array([[1, 2],
              [3, 4]])
y = np.expand_dims(x,axis=0)
print(y,y.shape)
yy = np.squeeze(y,axis=0)
print(yy,yy.shape)
print("-"*80)
y = np.expand_dims(x,axis=1)
print(y,y.shape)
yy = np.squeeze(y,axis=1)
print(yy,yy.shape)
print("-"*80)
y = np.expand_dims(x,axis=2)
print(y,y.shape)
yy = np.squeeze(y,axis=2)
print(yy,yy.shape)
print("-"*80)

[[[1 2]
  [3 4]]] (1, 2, 2)
[[1 2]
 [3 4]] (2, 2)
--------------------------------------------------------------------------------
[[[1 2]]

 [[3 4]]] (2, 1, 2)
[[1 2]
 [3 4]] (2, 2)
--------------------------------------------------------------------------------
[[[1]
  [2]]

 [[3]
  [4]]] (2, 2, 1)
[[1 2]
 [3 4]] (2, 2)
--------------------------------------------------------------------------------


### Concatenate

In [22]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
print(np.concatenate((a, b), axis=0))
print(np.concatenate((a, b), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [29]:
array_1 = np.array([[1,2,3],
                    [0,0,0]])

array_2 = np.array([[0,0,0],
                    [7,8,9]])

print(np.concatenate((array_1, array_2), axis = 1))

[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]


### stack

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.stack((a, b), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

### vstack

In [16]:
a = np.array([[1], 
              [2], 
              [3]])
b = np.array([[4],
              [5], 
              [6]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### hstack

In [17]:
a = np.array([[1],
              [2],
              [3]])
b = np.array([[4],
              [5],
              [6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

### Block

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.block([a, b, 10]))
print(np.block([[a], [b]]))

[ 1  2  3  4  5  6 10]
[[1 2 3]
 [4 5 6]]
