### dot product

In [3]:
import numpy as np

In [12]:
a = [[1, 1], 
     [2, 2]]
b = [[1, 2], 
     [3, 4]]
print(np.dot(a, b))
print(np.inner(a, b))

[[ 4  6]
 [ 8 12]]
[[ 3  7]
 [ 6 14]]


In [13]:
a = [[1, 1], 
     [2, 2]]
b = [[1, 2], 
     [3, 4]]
np.matmul(a, b)

array([[ 4,  6],
       [ 8, 12]])

### v dot

In [7]:
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])
np.vdot(a, b)

(70-8j)

### inner

In [11]:
a = np.array([1,2,3])
b = np.array([2,1,2])
np.inner(a, b)

10

In [18]:
a = np.array([1,2,3])
b = np.array([2,1,2])
np.outer(a, b)

array([[2, 1, 2],
       [4, 2, 4],
       [6, 3, 6]])

## determinant

In [16]:
a = np.array([[5, 6],
              [13, 24]])
np.linalg.det(a)

42.00000000000002

In [17]:
abs(5*24-6*13)

42